name: CI NestJS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Sesuaikan dengan versi Node yang kamu pakai
        cache: 'npm'

    - name: Install dependencies
      run: npm ci # atau npm install jika kamu tidak pakai package-lock.json ketat

    # --- TAMBAHKAN DUA LANGKAH INI SEBELUM RUN TEST / BUILD ---
    - name: Cache Prisma Client
      uses: actions/cache@v4
      with:
        path: node_modules/.prisma
        key: ${{ runner.os }}-prisma-${{ hashFiles('**/schema.prisma') }}

    - name: Generate Prisma Client
      run: npx prisma generate
    # ----------------------------------------------------------

    - name: Run unit tests
      run: npm run test

    - name: Build application
      run: npm run build